In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
data = [1,2,3] #python list 

np_arr = np.array(data)

In [5]:
print(np_arr)

[1 2 3]


In [6]:
print(type(np_arr))

<class 'numpy.ndarray'>


In [8]:
#예제 1-2 Python Array 사용 : # 리스트멤버를 100을 곱하여 출력하기 

data = [1,2,3]

result = [] 

for i in data:
    result.append(i*100)
print(result)



[100, 200, 300]


In [11]:
#예제 1-3 Numpy ndarray 사용시 

nd_arr = np.array(data)

result = nd_arr * 100

print(result)

[100 200 300]


In [18]:
#예제 1-4 일반 Array 1행 선택 data2d[0] => [1,2,3]
data2d = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

print(data2d[0]) #열은 인덱스로 접근 가능하나 컬럼은 루프를 돌려야만 한다. 

[1, 2, 3]


In [19]:
#예제 1-5 numpy 객체 효육성 
data2d = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

arr = np.array(data2d)

print(arr[: ,0 ]) #첫 Column (행) 축출   
print(arr[0:1]) #첫 index (열) 루프없이 바로 값이 나온다. 


[1 4 7]
[[1 2 3]]


In [26]:
#ndarray 
data1 = [1,2,3,4]

arr1 = np.array(data1)
print(arr1)
print(type(arr1))
print(arr1.ndim) # 1 반환 
print(arr1.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
1
(4,)


In [21]:
data2d = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

arr2 = np.array(data2d)

print(arr2)
print(type(arr2))
print(type(arr2[0]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [22]:
print(arr2.shape)

(3, 3)


In [23]:
print(arr2.ndim) #2차원을 반환함. 

2


In [25]:
print(arr2.dtype)

int64
